In [37]:
import torch
#Use this space for manually computing the scaled dot product attention

In [5]:
input = torch.tensor([[-1.5898,1.5792,0.8666,1.0245],[2.2796,0.9813,1.4023,-0.6616],[0.1588,0.4028,-1.7044,-1.8284],[0.4366,-1.0197,-0.4217, 1.4877],[-0.8311,-0.1762,-1.8709,2.2313]], dtype=torch.float32)
input
#Paper example input from embedding layers

tensor([[-1.5898,  1.5792,  0.8666,  1.0245],
        [ 2.2796,  0.9813,  1.4023, -0.6616],
        [ 0.1588,  0.4028, -1.7044, -1.8284],
        [ 0.4366, -1.0197, -0.4217,  1.4877],
        [-0.8311, -0.1762, -1.8709,  2.2313]])

In [18]:
#Lets try to initialize the K,Q,V wieghts
import torch.nn as nn
import torch.nn.init as init

# Our example input has a column dimension of 4, or 4 featues in the sequence. 
# This is important for the linear layers
d_model = 4

# Set dimensions of the weights
W_Q = nn.Linear(d_model, d_model, bias=False)
W_K = nn.Linear(d_model, d_model, bias=False)
W_V = nn.Linear(d_model, d_model, bias=False)

nn.init.kaiming_normal_(W_Q.weight)
nn.init.kaiming_normal_(W_K.weight)
nn.init.kaiming_normal_(W_V.weight)

print(W_Q.weight)
print(W_K.weight)
print(W_V.weight)



Parameter containing:
tensor([[-0.0167, -0.3836,  0.3057, -1.6176],
        [-0.9095, -0.3848, -0.5388,  0.6638],
        [ 0.3014, -0.3997, -0.4050,  0.3834],
        [ 0.1564, -0.5142, -0.8222, -0.5973]], requires_grad=True)
Parameter containing:
tensor([[-0.4236,  0.4587,  0.4679,  1.3346],
        [ 0.0984, -0.1086, -0.0687, -0.4526],
        [ 0.1896, -0.1889, -0.5235,  0.0708],
        [-0.8764, -0.2409, -0.3299, -0.5605]], requires_grad=True)
Parameter containing:
tensor([[ 0.0811, -0.1623,  1.5385,  0.6436],
        [ 1.5437, -0.3447, -0.6894,  0.0305],
        [ 0.2190,  0.6618,  0.5555,  0.0452],
        [ 1.3458,  0.1445, -0.2622, -0.0180]], requires_grad=True)


In [70]:
import math
# Lets compute Q,K,V first linear projection
with torch.no_grad():
    Q = W_Q(input)
    K = W_K(input)
    V = W_V(input)
    print("Q vector:")
    printTensor(Q)
    print("K vector:")
    printTensor(K)
    print("V vector:",)
    printTensor(V)
    # Scaled dot-product
    attention_weights = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(d_model)
    print("Scaled Dot Product:")
    printTensor(attention_weights)
    #softmax
    attention_weights.softmax(-1)
    print("Softmax:")
    printTensor(attention_weights)
    #Last linear layer
    print("Output:")
    output = torch.matmul(attention_weights, V)
    printTensor(output)

Q vector:
          0         1         2         3
0 -1.971605  1.051457 -1.068663 -2.385256
1  1.084435 -3.645744 -0.526604 -0.905841
2  2.279399 -0.594955 -0.123899  2.311266
3 -2.151566  1.210121  1.280348  0.050730
4 -4.099931  3.312943  1.432984  0.166065
K vector:
          0         1         2         3
0  3.170568 -0.851225 -0.981001  0.152647
1 -0.742425  0.320789 -0.533969 -2.326051
2 -3.120222  0.916468  0.716774  1.350953
3  1.135578 -0.490544  0.601512 -0.831683
4  2.373835 -0.943862  1.012947  0.137440
V vector:
          0         1         2         3
0  1.607486 -3.564692  1.224613 -2.157120
1  1.757219  2.193852  1.897804  2.854013
2 -3.851525  1.225622 -0.728067  0.751833
3  0.509565  1.361481 -0.746195  0.523980
4 -1.481155  0.135552 -1.237002 -0.693649


TypeError: printTensor() takes 1 positional argument but 2 were given

In [69]:
#This is how you'll do diagrams for tensors from here on out
import pandas as pd
#pd.DataFrame(input)

def printTensor(tensor):
    df = pd.DataFrame(tensor)
    print(df)

If a tensor requires grads, use this method,
# Convert the tensor to a numpy array
tensor_numpy = tensor.cpu().numpy()

# Create a DataFrame using the numpy array
df = pd.DataFrame(tensor_numpy)

# Display the DataFrame
print(df)